package com.example.ali.letthemknow;

/**
 * Created by Ali on 2/4/2017.
 */
import android.content.Context;
import android.net.Uri;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;
import android.hardware.*;


/**
 * A simple {@link Fragment} subclass.
 * Activities that contain this fragment must implement the
 * {@link PedFragment.OnFragmentInteractionListener} interface
 * to handle interaction events.
 * Use the {@link PedFragment#newInstance} factory method to
 * create an instance of this fragment.
 */
public class PedFragment extends Fragment implements SensorEventListener {

    //These vars are what I added for pedometer
    private SensorManager sensorManager;
    private TextView count;
    boolean fragmentRunning;
    private Button resetButton;


// This block of code was generated by the SDK when I created the Fragment

    // TODO: Rename parameter arguments, choose names that match
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
    private static final String ARG_PARAM1 = "param1";
    private static final String ARG_PARAM2 = "param2";
    private float lastValue = 0;
    // TODO: Rename and change types of parameters
    private String mParam1;
    private String mParam2;

    private OnFragmentInteractionListener mListener;

    public PedFragment() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment PedFragment.
     */
    // TODO: Rename and change types and number of parameters
    public static PedFragment newInstance(String param1, String param2) {
        PedFragment fragment = new PedFragment();
        Bundle args = new Bundle();
        args.putString(ARG_PARAM1, param1);
        args.putString(ARG_PARAM2, param2);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context instanceof OnFragmentInteractionListener) {
            mListener = (OnFragmentInteractionListener) context;
        } else {
            throw new RuntimeException(context.toString()
                    + " must implement OnFragmentInteractionListener");
        }
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //fragment must make extra call to getActivity() before getSystemService
        sensorManager = (SensorManager) getActivity().getSystemService(Context.SENSOR_SERVICE);


        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        /*
        fragment must make extra call to getView() before calling findViewByID
        getView() fxn can't be used in onCreate() for fragment must be used here
        these two lines i added the return inflate line Android SDK autogenerated
        findViewById may throw a NullPointerException that I have not handled yet
        */
        View view = inflater.inflate(R.layout.fragment_ped, container, false);
        count = (TextView) view.findViewById(R.id.count);
        resetButton = (Button) view.findViewById(R.id.reset);
        resetButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                lastValue =  Float.parseFloat(count.getText().toString());
                count.setText("0");
            }
        });
        // Inflate the layout for this fragment
        return view;
    }

    // TODO: Rename method, update argument and hook method into UI event
    public void onButtonPressed(Uri uri) {
        if (mListener != null) {
            mListener.onFragmentInteraction(uri);

        }
    }


    /**
     * This interface must be implemented by activities that contain this
     * fragment to allow an interaction in this fragment to be communicated
     * to the activity and potentially other fragments contained in that
     * activity.
     * <p>
     * See the Android Training lesson <a href=
     * "http://developer.android.com/training/basics/fragments/communicating.html"
     * >Communicating with Other Fragments</a> for more information.
     */
    public interface OnFragmentInteractionListener {
        // TODO: Update argument type and name
        void onFragmentInteraction(Uri uri);
    }


    @Override
    public void onResume() {
        super.onResume();
        fragmentRunning = true;
        Sensor countSensor = sensorManager.getDefaultSensor(Sensor.TYPE_STEP_COUNTER);
        if (countSensor != null) {
            sensorManager.registerListener(this, countSensor, SensorManager.SENSOR_DELAY_UI);
        } else {
            Toast.makeText(PedFragment.this.getActivity(), "Count sensor not available!", Toast.LENGTH_LONG).show();
        }

    }

    @Override
    public void onPause() {
        super.onPause();
        fragmentRunning = false;
// if you unregister the last listener, the hardware will stop detecting step events
// sensorManager.unregisterListener(this);
    }


    @Override
    public void onSensorChanged(SensorEvent event) {
        if (fragmentRunning) {
            count.setText(String.valueOf(event.values[0] - lastValue));
        }
    }

    @Override
    public void onAccuracyChanged(Sensor sensor, int accuracy) {
        /*
        Complete the function definition if we want to do anything
        differently when the accuracy of the sensor changes
        */
    }

    @Override
    public void onDetach() {
        super.onDetach();
        mListener = null;
    }

} // end of class PedFragment
